### ISSUE TITLE
Pathfinding

### ISSUE THREAD

**Issue by aethura** [asiudhgfiuashgiuashg/tile-game#1]
We gotta implement this shit

**Comment by mikeadkison** [comment]
Needs to be done server-side. Also the server needs to have a concept of maps

**Comment by mikeadkison** [comment]
## 2 Phases of pathfinding

### Preprocessing
- generate a graph given a map

### Real time pathfinding
- find a path through the graph

![phase1](https://cloud.githubusercontent.com/assets/5761270/11916522/21c21a94-a6a8-11e5-99ff-3bbb2306e532.png)
![phase2](https://cloud.githubusercontent.com/assets/5761270/11916524/21c80da0-a6a8-11e5-8165-815adf56b60c.png)
![phase1_realtime](https://cloud.githubusercontent.com/assets/5761270/11916523/21c702a2-a6a8-11e5-92e0-782ee574e931.png)
![phase2_realtime](https://cloud.githubusercontent.com/assets/5761270/11916525/21d21980-a6a8-11e5-869b-decdca113819.png)

## TODO
- implement or find a graph representation
- implement or find path finding
- figure out how to save the generated graphs

**Comment by mikeadkison** [comment]
decided to use [IndexedAStarPathFinder](https://libgdx.badlogicgames.com/gdx-ai/docs/com/badlogic/gdx/ai/pfa/indexed/IndexedAStarPathFinder.html)

**Comment by mikeadkison** [comment]
https://github.com/asiudhgfiuashgiuashg/tile-game/commit/cc1374ac35053d7016ba1fb7680a5574004fa79e

implemented pathfinding, you can test it with the simple TestAi instance in single player.

### TODO
- sync Agents with clients (multiplayer)

**Comment by mikeadkison** [comment]
ima close this since we no longer use github for issue tracking
